services:
  postgresql:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=db
    ports:
      - "${DATABASE_LOCAL_PORT:-5432}:5432"
    healthcheck:
      test: 'pg_isready -d kafka-transactions -h 0.0.0.0 -U postgres'
      interval: 2s
      timeout: 60s
      retries: 30
    volumes:
      - ./src/main/resources/postgres_script.sql:/docker-entrypoint-initdb.d/postgres_script.sql
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 2s
      timeout: 60s
      retries: 30
  broker:
    image: confluentinc/cp-kafka:7.2.3
    ports:
      - "${KAFKA_LOCAL_PORT:-9092}:9092"
      - "${KAFKA_JMX_LOCAL_PORT:-9997}:9997"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=broker -Dcom.sun.management.jmxremote.rmi.port=9997
    healthcheck:
      test: "kafka-topics --bootstrap-server localhost:9092 --list"
      interval: 2s
      timeout: 60s
      retries: 30
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - '9090:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:29092"
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
networks:
  default:
    name: kafka-transactions
